name: 'dbt_stellantis'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  dbt_stellantis:
    staging:
      materialized: view
    intermediate:
      materialized: ephemeral
    marts:
      core:
        materialized: table
